services:
  db:
    image: postgres:16-alpine
    container_name: locadora_dwh_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: locadora_dwh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_dwh_data:/var/lib/postgresql/data
      # Monta a pasta sql em /sql (NÃO dentro de initdb.d, para evitar execução automática)
      - ./sql:/sql:ro
      # Apenas o init-db.sh vai dentro de initdb.d, controlando a ordem de execução
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

volumes:
  postgres_dwh_data:
